// resources/js/components/MyDrive/ContextMenu.tsx
import { useState, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';
import { useMediaStore } from '@/stores/mediaStore';
import { useLocation } from 'react-router-dom';
import {
    EyeIcon,
    UsersIcon,
    LinkIcon,
    StarIcon,
    ArrowRightIcon,
    PencilIcon,
    DocumentDuplicateIcon,
    ArrowDownTrayIcon,
    TrashIcon,
    FolderPlusIcon,
    ArrowUpTrayIcon,
    FolderOpenIcon,
    ArrowPathIcon,
    XCircleIcon,
} from '@heroicons/react/24/outline';
import type { ComponentType } from 'react';
import type { MediaFile } from '@/types';

interface ContextMenuProps {
    show: boolean;
    x: number;
    y: number;
    file?: Partial<MediaFile>;
    onClose: () => void;
    onOpenDropZone?: () => void;
    onUploadFolder?: () => void;
}

interface MenuItem {
    title: string;
    Icon: ComponentType<{ className?: string }>;
    show: string;
    action: () => void;
}

export default function ContextMenu({ show, x, y, file, onClose, onOpenDropZone, onUploadFolder }: ContextMenuProps) {
    const store = useMediaStore();
    const location = useLocation();
    const selectedFilesId = store.selectedFilesId;

    const manageStar = () => {
        if (file?.id === undefined) return;
        if (file.stared) {
            store.removeStar(selectedFilesId);
        } else {
            store.addStar(selectedFilesId);
        }
    };

    const menuitems: MenuItem[] = [
        { title: 'Preview', Icon: EyeIcon, show: 'items', action: () => store.setPreviewModal(true) },
        { title: 'Share', Icon: UsersIcon, show: 'items', action: () => store.setShareFileModal(true) },
        { title: 'Get shareable link', Icon: LinkIcon, show: 'items', action: () => store.setShareLinkModal(true) },
        { title: file?.stared ? 'Remove from star' : 'Add a star', Icon: StarIcon, show: 'items', action: manageStar },
        { title: 'Move to', Icon: ArrowRightIcon, show: 'items', action: () => store.setMoveToModal(true) },
        { title: 'Rename', Icon: PencilIcon, show: 'items', action: () => store.setRenameFileModal(true) },
        { title: 'Make a copy', Icon: DocumentDuplicateIcon, show: 'items', action: () => store.copyFile(selectedFilesId) },
        { title: 'Download', Icon: ArrowDownTrayIcon, show: 'items', action: () => store.downloadFile(selectedFilesId) },
        { title: 'Delete', Icon: TrashIcon, show: 'items', action: () => store.deleteItem({ ids: selectedFilesId }) },
        { title: 'New Folder', Icon: FolderPlusIcon, show: 'back', action: () => store.setNewFolderModal(true) },
        { title: 'Upload files', Icon: ArrowUpTrayIcon, show: 'back', action: () => onOpenDropZone?.() },
        { title: 'Upload Folder', Icon: FolderOpenIcon, show: 'back', action: () => onUploadFolder?.() },
        { title: 'Restore files', Icon: ArrowPathIcon, show: 'trash', action: () => store.deleteItem({ ids: selectedFilesId, action: 'restore' }) },
        { title: 'Delete Forever', Icon: XCircleIcon, show: 'trash', action: () => store.deleteItem({ ids: selectedFilesId, action: 'deleteforever' }) },
    ];

    const pathname = location.pathname;
    const items = (() => {
        if (file?.id !== undefined && file.deleted_at === null) {
            const fileItems = menuitems.filter((i) => i.show === 'items');
            return file.type === 'folder' ? fileItems.filter((i) => i.title !== 'Preview') : fileItems;
        } else if (file?.id !== undefined && file.deleted_at !== null) {
            return menuitems.filter((i) => i.show === 'trash');
        } else if (pathname === '/media' || pathname.startsWith('/media/folder')) {
            return menuitems.filter((i) => i.show === 'back');
        }
        return [];
    })();

    if (!show || items.length === 0) return null;

    return createPortal(
        <>
            <div className="fixed inset-0 z-50" onClick={onClose} />
            <div
                className="fixed z-50 w-56 rounded-lg bg-white py-1.5 shadow-xl ring-1 ring-gray-200"
                style={{ left: x, top: y }}
            >
                {items.map((item, index) => (
                    <button
                        key={index}
                        className="flex w-full items-center gap-3 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
                        onClick={() => { item.action(); onClose(); }}
                    >
                        <item.Icon className="h-4 w-4 text-gray-400" />
                        <span>{item.title}</span>
                    </button>
                ))}
            </div>
        </>,
        document.body
    );
}

// resources/assets/admin/src/components/MyDrive/ContextMenu.vue
<template>
    <VMenu
        v-if="items.length"
        v-model="showMenu"
        :position-x="x"
        :position-y="y"
        absolute
        offset-y
    >
        <VList id="contextmenu">
            <VListTile
                v-for="(item, index) in items"
                :key="index"
                ripple
                @click="item.action"
            >
                <VListTileAction v-if="item.icon">
                    <VIcon>{{ item.icon }}</VIcon>
                </VListTileAction>
                <VListTileTitle>{{ item.title }}</VListTileTitle>
            </VListTile>
        </VList>
    </VMenu>
</template>

<script>
import { mapState } from 'vuex'
import Mixins from './mixin'

export default {
    mixins: [Mixins],
    props: {
        value: {
            type: Boolean
        },
        x: {
            type: Number,
            default: 0
        },
        y: {
            type: Number,
            default: 0
        },
        file: {
            type: Object,
            default () {
                return {

                }
            }
        }
    },
    data () {
        return {
            showMenu: this.value
        }
    },
    watch: {

        value (newVal) {
            this.showMenu = false
            this.$nextTick(() => {
                this.showMenu = newVal
            })
        },
        x () {
            this.showMenu = false
            this.$nextTick(() => {
                this.showMenu = true
            })
        },
        y () {
            this.showMenu = false
            this.$nextTick(() => {
                this.showMenu = true
            })
        }
    },
    computed: {
        ...mapState('Media', ['selectedFilesId']),
        items () {
            if (this.file.hasOwnProperty('id') && this.file.deleted_at === null) {
                return this.menuitems.filter(i => i.show === 'items')
            } else if (this.file.hasOwnProperty('id') && this.file.deleted_at !== null) {
                return this.menuitems.filter(i => i.show === 'trash')
            } else if (this.$route.name === 'media' || this.$route.name === 'singleFolder') {
                return this.menuitems.filter(i => i.show === 'back')
            }

            return []
        },

        menuitems () {
            return [
                {
                    title: 'Preview',
                    icon: 'visibility',
                    show: 'items',
                    action: ''
                },
                {
                    title: 'Share',
                    icon: 'supervisor_account',
                    show: 'items',
                    action: this.shareFiles
                },
                {
                    title: 'Get shareable link',
                    icon: 'link',
                    show: 'items',
                    action: ''
                },
                {
                    title: this.file.stared ? 'Removed from star' : 'Add a star',
                    icon: 'grade',
                    show: 'items',
                    action: this.manageStar
                },
                {
                    title: 'Move to',
                    icon: 'call_missed_outgoing',
                    show: 'items',
                    action: this.moveTo
                },
                {
                    title: 'Rename',
                    icon: 'edit',
                    show: 'items',
                    action: this.openRenameModel
                },
                {
                    title: 'Make a copy',
                    icon: 'file_copy',
                    show: 'items',
                    action: this.copyFiles
                },
                {
                    title: 'Download',
                    icon: 'cloud_download',
                    show: 'items',
                    action: this.downloadFile
                },
                {
                    title: 'Delete',
                    icon: 'delete',
                    show: 'items',
                    action: this.deleteItems
                },
                {
                    title: 'New Folder',
                    icon: 'create_new_folder',
                    show: 'back',
                    action: this.openNewFolderModal
                },
                {
                    title: 'Upload files',
                    icon: 'cloud_upload',
                    show: 'back',
                    action: this.openDropZone
                },
                {
                    title: 'Upload Folder',
                    icon: 'folder_open',
                    show: 'back',
                    action: this.uploadFolder
                },
                {
                    title: 'Restore files',
                    icon: 'restore',
                    show: 'trash',
                    action: this.restore
                },
                {
                    title: 'Delete Forever',
                    icon: 'delete_forever',
                    show: 'trash',
                    action: this.deleteForever
                }
            ]
        }
    },
    methods: {
        openDropZone () {
            Bus.$emit('openDropZone')
        },
        uploadFolder () {
            Bus.$emit('uploadFolder')
        },
        moveTo () {
            Bus.$emit('moveTo', true)
        },
        shareFiles () {
            this.$store.commit('Media/shareFileModal', true)
        },
        manageStar () {
            if (this.file.hasOwnProperty('id') && !this.file.stared) {
                this.$store.dispatch('Media/addStar', { ids: this.selectedFilesId })
            } else {
                this.$store.dispatch('Media/removeStar', { ids: this.selectedFilesId })
            }
        },
        openRenameModel () {
            this.$store.commit('Media/renamefilemodal', true)
        },

        deleteItems () {
            this.$store.dispatch('Media/deleteItem', { ids: this.selectedFilesId })
        },
        copyFiles () {
            this.$store.dispatch('Media/copyFile', { ids: this.selectedFilesId })
        },
        downloadFile () {
            this.$store.dispatch('Media/downloadFile', { ids: this.selectedFilesId })
        },
        restore () {
            this.$store.dispatch('Media/deleteItem', { ids: this.selectedFilesId, action: 'restore' })
        },
        deleteForever () {
            this.$store.dispatch('Media/deleteItem', { ids: this.selectedFilesId, action: 'deleteforever' })
        }
    }
}
</script>

<style>
    #contextmenu {
        width: 300px;
        padding: 10px;
    }
    #contextmenu .v-list__tile.theme--light:hover {
        background: #f3f3f3;
    }
    #contextmenu .v-list__tile__action {
        min-width: 36px;
    }
    #contextmenu .v-list__tile {
        height: 32px;
        cursor: pointer;
    }
</style>
