// resources/js/components/MyDrive/SharedWithMe.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useSearchParams, useNavigate, useLocation } from 'react-router-dom';
import { useMediaStore } from '@/stores/mediaStore';
import MediaItem from './MediaItem';
import MediaInfo from './MediaInfo';
import FileUploader from './FileUploader';
import ContextMenu from './ContextMenu';
import NewFolderForm from './NewFolderForm';
import ShareFile from './ShareFile';
import RenameFile from './RenameFile';
import MoveTo from './MoveTo';
import type { MediaFile } from '@/types';

export default function SharedWithMe() {
    const { folderId } = useParams();
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();
    const location = useLocation();
    const store = useMediaStore();

    const [isLoaded, setIsLoaded] = useState(false);
    const [fileUploader, setFileUploader] = useState(false);
    const [scrollLoading, setScrollLoading] = useState(false);
    const [clickedOnItem, setClickedOnItem] = useState(false);
    const [cm, setCm] = useState<{ show: boolean; x: number; y: number; file?: Partial<MediaFile> }>({ show: false, x: 0, y: 0 });
    const fileCmRef = useRef(false);

    const { sharedItems, sharedPagination, fileInfoSideBar, newFolderModal, shareFileModal, renameFileModal } = store;

    const loadItems = useCallback(() => {
        const params: Record<string, unknown> = {};
        if (folderId) params.parent_id = folderId;
        const page = searchParams.get('page');
        if (page) params.page = Number(page);
        store.fetchSharedItems(params).then(() => {
            setIsLoaded(true);
            setScrollLoading(false);
        });
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [folderId, searchParams]);

    useEffect(() => { loadItems(); }, [loadItems]);
    useEffect(() => { return () => { useMediaStore.getState().emptySharedItems(); }; }, []);

    useEffect(() => {
        const handler = (event: MouseEvent) => {
            if ((event.target as HTMLElement).closest('button.media-info-button')) return;
            if (!clickedOnItem) store.deselectFile();
            setClickedOnItem(false);
        };
        document.addEventListener('click', handler);
        return () => document.removeEventListener('click', handler);
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [clickedOnItem]);

    useEffect(() => {
        const handler = () => {
            if (scrollLoading) return;
            const bottomOfWindow = document.documentElement.scrollTop + window.innerHeight + 50 > document.documentElement.offsetHeight;
            if (bottomOfWindow) {
                const currentPage = Number(searchParams.get('page') || 1);
                const nextPage = currentPage + 1;
                if (sharedPagination.total_pages && nextPage > sharedPagination.total_pages) return;
                setScrollLoading(true);
                const params = new URLSearchParams(searchParams);
                params.set('page', String(nextPage));
                navigate(`${location.pathname}?${params.toString()}`, { replace: true });
            }
        };
        window.addEventListener('scroll', handler);
        return () => window.removeEventListener('scroll', handler);
    }, [scrollLoading, searchParams, sharedPagination, navigate, location.pathname]);

    const showContextMenu = (e: React.MouseEvent) => {
        e.preventDefault();
        if (fileCmRef.current) { fileCmRef.current = false; return; }
        setCm({ show: true, x: e.clientX, y: e.clientY });
    };

    const showContextMenu2 = (e: React.MouseEvent, item: MediaFile) => {
        e.preventDefault();
        fileCmRef.current = true;
        setCm({ show: true, x: e.clientX, y: e.clientY, file: item });
        onClickItem(e, item);
    };

    const onClickItem = (event: React.MouseEvent | React.TouchEvent, item: MediaFile) => {
        setClickedOnItem(true);
        const isMultiSelect = 'ctrlKey' in event && (event.ctrlKey || event.metaKey);
        if (!isMultiSelect && item.type === 'folder' && !fileCmRef.current) {
            navigate(`/media/shared/${item.hash}`);
        }
        store.selectFiles(item.id, !!isMultiSelect);
        store.selectMediaItem(item);
    };

    return (
        <div>
            {isLoaded ? (
                <div className={`relative mt-4 ${fileInfoSideBar ? 'mr-80' : ''}`} onContextMenu={showContextMenu}>
                    <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
                        {sharedItems.map((img) => (
                            <div key={img.id} onContextMenu={(e) => showContextMenu2(e, img)} onClick={(e) => onClickItem(e, img)} onTouchStart={(e) => onClickItem(e, img)}>
                                <MediaItem media={img} />
                            </div>
                        ))}
                    </div>
                    {!sharedItems.length && (
                        <div className="flex flex-col items-center justify-center py-20 text-center">
                            <svg className="mb-4 h-16 w-16 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                            <p className="text-sm text-gray-500">No files shared with you</p>
                        </div>
                    )}
                    {fileInfoSideBar && <MediaInfo />}
                    <FileUploader active={fileUploader} onDeactivate={() => setFileUploader(false)} currentFolderId={0} />
                    <ContextMenu show={cm.show} x={cm.x} y={cm.y} file={cm.file} onClose={() => setCm({ show: false, x: 0, y: 0 })} />
                </div>
            ) : (
                <div className="flex items-center justify-center py-20">
                    <svg className="h-8 w-8 animate-spin text-brand-600" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                </div>
            )}
            {newFolderModal && <NewFolderForm open={newFolderModal} />}
            {shareFileModal && <ShareFile open={shareFileModal} />}
            {renameFileModal && <RenameFile open={renameFileModal} />}
            <MoveTo open={store.moveToModal} />
        </div>
    );
}

// resources/assets/admin/src/components/MyDrive/SharedWithMe.vue
<template>
    <VLayout class="d-block">
        <VLayout
            v-if="isLoaded"
            fill-height
            :class="{'my-file': true, 'sidebar-open': fileInfoSideBar}"
            @dragenter="activeDropzone($event)"
            @contextmenu="showContextMenu"
        >
            <VLayout
                id="filecontainer"
                row
                wrap
            >
                <VFlex
                    v-for="img in sharedItems"
                    :key="img.id"
                    @contextmenu="showContextMenu2($event, img)"
                    @click="OnClickItem($event, img)"
                    @touchstart="OnClickItem($event, img)"
                >
                    <MediaItem :media="img" />
                </VFlex>
            </VLayout>

            <MediaInfo v-if="fileInfoSideBar" />
            <FileUploader v-model="fileUploader" />
            <!-- <context-menu v-model="cm.show" :x="cm.x" :y="cm.y" /> -->
            <ContextMenu
                v-model="cm.show"
                :x="cm.x"
                :y="cm.y"
                :file="cm.file"
            />
        </VLayout>
        <template v-if="newFolderModal">
            <NewFolderForm :open="newFolderModal" />
        </template>
        <template v-if="shareFileModal">
            <ShareFile :open="shareFileModal" />
        </template>
        <template v-if="renamefilemodal">
            <RenameFile :open="renamefilemodal" />
        </template>

        <MoveTo />
    </VLayout>
</template>

<script>
import { mapState } from 'vuex'
import FileUploader from './FileUploader.vue'
import MediaItem from './mediaItem.vue'
import MediaInfo from './MediaInfo.vue'
import Mixins from './mixin'
import NewFolderForm from './NewFolderForm.vue'
import ShareFile from './ShareFile.vue'
import RenameFile from './RenameFile.vue'
import ContextMenu from './ContextMenu.vue'
import MoveTo from './MoveTo.vue'

export default {
    components: {
        FileUploader,
        MediaItem,
        MediaInfo,
        NewFolderForm,
        RenameFile,
        ContextMenu,
        MoveTo,
        ShareFile
    },
    mixins: [Mixins],
    data () {
        return {
            cm: {},
            cm2: {},
            fileUploader: false,
            scrollLoading: false,
            fileCm: false,
            clickedOnItem: false
        }
    },
    computed: {
        ...mapState('Media', ['sharedItems', 'sharedPagination', 'fileInfoSideBar', 'newFolderModal', 'shareFileModal', 'renamefilemodal']),
        isLoaded () {
            return this.isfilesLoaded
        }
    },
    watch: {
        '$route' (to, from) {
            this.selfMddiaItems(to)
        }
    },
    created () {
        this.selfMddiaItems(this.$route)
    },
    mounted () {
        document.addEventListener('click', (event) => {
            let element = event.target.closest('button.media-info-button')

            if (element) {
                return
            }

            this.deselect()
        })
        this.scroll()
    },
    destroyed () {
        this.$store.commit('Media/emptySharedItems')
    },
    methods: {
        selfMddiaItems (route) {
            let params = {}
            if (typeof route.params.folderId !== 'undefined') {
                params.parent_id = route.params.folderId
            }
            if (route.query.page) {
                params.page = route.query.page
            }

            this.$store.dispatch('Media/getSharedItems', params)
                .then(() => {
                    this.isfilesLoaded = true
                    this.scrollLoading = false
                })
        },
        activeDropzone (event) {
            event.stopPropagation()
            event.preventDefault()
            this.fileUploader = true
        },
        showContextMenu (e, item) {
            e.preventDefault()

            if (this.fileCm) {
                this.fileCm = false
                return
            }

            this.cm = {
                show: true,
                x: e.clientX,
                y: e.clientY,
                file: item
            }
        },
        showContextMenu2 (e, item) {
            e.preventDefault()
            this.fileCm = true
            this.cm = {
                show: true,
                x: e.clientX,
                y: e.clientY,
                file: item
            }
            this.OnClickItem(e, item)
        },
        OnClickItem (event, item) {
            this.clickedOnItem = true
            let isMultiSelect = event.ctrlKey || event.metaKey

            if (!isMultiSelect && item.type === 'folder' && !this.fileCm) {
                this.pushChiled(item)
            }

            this.$store.commit('Media/selectFiles', { isMultiSelect: isMultiSelect, id: item.id })
            this.$store.commit('Media/selectMediaItem', item)
        },
        pushChiled (item) {
            let name = 'sharedFolder'
            this.$router.push({
                name: name,
                params: {
                    folderId: item.hash
                }
            })
        },
        deselect () {
            if (this.clickedOnItem) {
                this.clickedOnItem = false
                return
            }

            this.$store.commit('Media/deselectFile')
        },
        scroll () {
            window.onscroll = () => {
                if (this.scrollLoading) {
                    return
                }
                let bottomOfWindow = document.documentElement.scrollTop + window.innerHeight + 50 > document.documentElement.offsetHeight

                if (bottomOfWindow) {
                    let page = (this.$route.query.page || 1) + 1
                    if (page > this.sharedPagination.total_pages) {
                        return
                    }

                    this.scrollLoading = true

                    this.$router.replace({
                        name: this.$route.name,
                        params: this.$route.params,
                        query: {
                            page: page
                        }
                    })
                }
            }
        }

    }
}
</script>

<style lang="scss">
div#laraveladmin {
    width: 100%;
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    display: none;
    opacity: 0;
}
.media-item .v-card__actions button.v-btn {
    width: 12px;
    height: 12px;

}
.media-item .v-card__actions button.v-btn .v-icon {
    font-size: 12px;
}
.la-pt .v-toolbar__title {
    font-size: 18px;
    font-family: 'Roboto', sans-serif !important;
    font-weight: normal;
}
.la-pt .v-icon {
    font-size: 18px;
}
.la-pt .v-menu {
    margin-left: -14px;
}
.my-file {
    position: relative;
    display: block;
    overflow: hidden;
}
#filecontainer {
    margin: 0;
    transition: 0.2s cubic-bezier(0.4, 0, 0.2, 1);
}
#filecontainer .flex {
    width: calc(20% - 20px);
    margin-top: 16px;
    margin-right: 20px;
    display: inline-block;
    position: relative;
    vertical-align: top;
    max-width: 210px;
    min-width: 120px;
}
.sidebar-open #filecontainer {
    margin-right: 300px;
}
.sidebar-open #filecontainer .flex {
    width: calc(25% - 20px);
}
</style>
