// resources/js/components/MyDrive/MediaInfo.tsx
import { useState } from 'react';
import { useMediaStore } from '@/stores/mediaStore';
import {
    FolderIcon,
    DocumentIcon,
    DocumentTextIcon,
    PhotoIcon,
    FilmIcon,
    MusicalNoteIcon,
    ArchiveBoxIcon,
} from '@heroicons/react/24/outline';
import type { ComponentType } from 'react';

const imageTypes = ['gif', 'ico', 'jpeg', 'jpg', 'png', 'svg', 'bmp', 'dib'];

export default function MediaInfo() {
    const [tabActive, setTabActive] = useState(1);
    const selectedMedia = useMediaStore((s) => s.selectedMedia);

    const hasItem = selectedMedia?.id !== undefined;

    const isImageFile = hasItem && imageTypes.includes(selectedMedia.extension || '');

    const getIcon = (): ComponentType<{ className?: string }> => {
        const ext = selectedMedia?.extension || '';
        const type = selectedMedia?.type || '';
        if (type === 'folder') return FolderIcon;
        if (imageTypes.includes(ext)) return PhotoIcon;
        if (['pdf', 'txt', 'doc', 'docx'].includes(ext)) return DocumentTextIcon;
        if (['mp4', 'webm', 'mov'].includes(ext)) return FilmIcon;
        if (['mp3', 'ogg'].includes(ext)) return MusicalNoteIcon;
        if (['zip', 'rar', '7z'].includes(ext)) return ArchiveBoxIcon;
        return DocumentIcon;
    };

    const getIconColor = (): string => {
        const ext = selectedMedia?.extension || '';
        const type = selectedMedia?.type || '';
        if (type === 'folder') return 'text-amber-500';
        if (imageTypes.includes(ext)) return 'text-emerald-500';
        if (['pdf'].includes(ext)) return 'text-red-500';
        return 'text-gray-400';
    };

    const Icon = getIcon();

    const details = hasItem
        ? [
              { label: 'File Name', value: selectedMedia.name },
              { label: 'Type', value: selectedMedia.type },
              { label: 'Size', value: selectedMedia.file_size },
              { label: 'Storage Used', value: selectedMedia.file_size },
              { label: 'Location', value: selectedMedia.url },
              { label: 'Owner', value: selectedMedia.file_name },
              { label: 'Created', value: selectedMedia.created_at?.date },
              { label: 'Modified', value: selectedMedia.updated_at?.date },
              { label: 'Description', value: selectedMedia.description },
          ].filter((d) => d.value)
        : [];

    return (
        <aside className="absolute inset-y-0 right-0 z-10 w-80 border-l border-gray-200 bg-white shadow-lg">
            {/* Header */}
            <div className="flex items-center gap-3 border-b border-gray-200 px-4 py-3">
                {hasItem ? (
                    <>
                        <Icon className={`h-5 w-5 shrink-0 ${getIconColor()}`} />
                        <h3 className="truncate text-sm font-semibold text-gray-900">{selectedMedia.name}</h3>
                    </>
                ) : (
                    <>
                        <FolderIcon className="h-5 w-5 text-amber-500" />
                        <h3 className="text-sm font-semibold text-gray-900">My Files</h3>
                    </>
                )}
            </div>

            {/* Tabs */}
            <div className="flex border-b border-gray-200">
                <button
                    className={`flex-1 py-2.5 text-center text-xs font-medium transition-colors ${tabActive === 1 ? 'border-b-2 border-brand-600 text-brand-700' : 'text-gray-500 hover:text-gray-700'}`}
                    onClick={() => setTabActive(1)}
                >
                    Details
                </button>
                <button
                    className={`flex-1 py-2.5 text-center text-xs font-medium transition-colors ${tabActive === 2 ? 'border-b-2 border-brand-600 text-brand-700' : 'text-gray-500 hover:text-gray-700'}`}
                    onClick={() => setTabActive(2)}
                >
                    Activities
                </button>
            </div>

            {hasItem ? (
                <div className="overflow-y-auto p-4" style={{ maxHeight: 'calc(100% - 110px)' }}>
                    {isImageFile && (
                        <img
                            src={selectedMedia.public_path}
                            alt={selectedMedia.name}
                            className="mb-4 w-full rounded-lg object-cover"
                            loading="lazy"
                        />
                    )}
                    <dl className="space-y-3">
                        {details.map((detail) => (
                            <div key={detail.label} className="flex gap-3">
                                <dt className="w-24 shrink-0 text-xs text-gray-500">{detail.label}</dt>
                                <dd className="break-all text-xs text-gray-900">{detail.value}</dd>
                            </div>
                        ))}
                    </dl>
                </div>
            ) : (
                <div className="flex flex-col items-center justify-center px-4 py-16 text-center">
                    <DocumentIcon className="mb-3 h-12 w-12 text-gray-300" />
                    <p className="text-sm text-gray-500">Select a file or folder to view its details.</p>
                </div>
            )}
        </aside>
    );
}

// resources/assets/admin/src/pages/media/MediaInfo.vue
<template>
    <v-navigation-drawer
        class="media-info"
        :value="fileInfoSideBar"
        absolute
        right
        >
       <div class="mi-fh" v-if="hasItem" >

           <span class="fn-i-i" :style="{ color: mediaIcon.color }" size="15" tile v-html="mediaIcon.icon"></span>
           <h3>{{ selectedMedia.name }}</h3>
       </div>

       <div class="mi-fh pa-3" v-else >

           <span class="fn-i-i" :style="{ color: mediaIcon.color }" size="15" tile v-html="mediaIcon.icon"></span>
           <h3>My Files </h3>
       </div>

       <div class="la-toggle-bn" >
           <a href="#" v-if="tabActive == 1" :class="{'active': tabActive == 1 }" >Details</a>
           <a href="#" v-if="tabActive == 1" :class="{'active': tabActive == 2 }"  >Activities</a>
       </div>

       <div class="details pa-3" v-if="hasItem" >
           <v-img
                :src="fileUrl"
                :lazy-src="fileUrl" >
                </v-img>
            
            <div class="las-info-list">
                <div class="las-ii">
                    <span class="la-ik">File Name</span>
                    <span class="la-iv">{{ selectedMedia.name }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Type</span>
                    <span class="la-iv">{{ selectedMedia.type }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Size</span>
                    <span class="la-iv">{{ selectedMedia.file_size }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Storate Used</span>
                    <span class="la-iv">{{ selectedMedia.file_size }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Location</span>
                    <span class="la-iv">{{ selectedMedia.url }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Owner</span>
                    <span class="la-iv">{{ selectedMedia.file_name }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Created</span>
                    <span class="la-iv">{{ selectedMedia.created_at.date }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Modified</span>
                    <span class="la-iv">{{ selectedMedia.updated_at.date }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">Description</span>
                    <span class="la-iv">{{ selectedMedia.description }}</span>
                </div>
                <div class="las-ii">
                    <span class="la-ik">File Name</span>
                    <span class="la-iv">{{ selectedMedia.file_name }}</span>
                </div>
            </div>
       </div>

       <div class="no-item pa-3" v-else >
           <v-icon color="gray" large>home</v-icon>

           <h4>Select a file or folder to view its details.</h4>
       </div> 

    </v-navigation-drawer>
</template>


<script>
import { mapState } from 'vuex';

import Mixins from './mixin';

export default {
    data () {
        return {
            tabActive: 1,
        }
    },
    mixins: [Mixins],
    computed: {
        ...mapState('Media', ['fileInfoSideBar', 'selectedMedia']),
        mediaIcon () {
            if (this.hasItem) {
                return this.getMediaIcon(this.selectedMedia.type)
            } else {
                return this.getMediaIcon('folder');
            }
        },
        fileUrl () {
            return window.location.origin +'/'+ this.selectedMedia.url;
        },
        hasItem () {
            return this.selectedMedia.hasOwnProperty('id');
        }
    },
    methods: {

    }
}
</script>

<style>
    .media-info {
        border-top: 1px solid #ddd;
    }
    .media-info .mi-fh {
        padding:20px 0px;
    }
    .media-info .mi-fh h3 {
        display: inline;
    }
    .la-toggle-bn {
        display: flex;
        justify-content: space-around;
        border-bottom: 1px solid #ddd;
    }
    .la-toggle-bn a {
        padding: 10px 20px;
        display: inline-block;
        font-size: 16px;
    }
    .la-toggle-bn a.active,
    .la-toggle-bn a:hover {
        text-decoration: none;
        border-bottom: 3px solid rgb(45, 111, 173);
    }
    .las-info-list {
        margin-top: 20px;
    }
    .las-ii {
        display: flex;
        justify-content: flex-start;
        align-items: self-start;
        padding: 7px 0px;
        text-overflow: clip;
        word-break: break-word;
        overflow: hidden;
    }

    .las-ii span.la-ik {
        flex: 0 0 120px;
        color: #757373;
    }
   

</style>
